### ISSUE TITLE
jsmart should support AMD and CMD

### ISSUE THREAD

**Issue by snadn** [umakantp/jsmart#10]
how can i use jsmart when there is not `module.exports = jSmart;` in jsmart.js.
and i dont think set `fetch` in `String.prototype` is a good way.

**Comment by umakantp** [comment]
Go ahead require jsmart js and use jSmart directly in all common js environments and browsers. You do not have to necessarily use String.prototype.fetch
e.g.
require('jsmart');
var compiledTpl = new jSmart('Hello {$name}');
console.log(compiledTpl.fetch({name: 'World'}));

**Comment by snadn** [comment]
oh, i know! I use like this `var jSmart = require('jsmart');`, so jSmart not that i expect.
use jsmart without defined is very very ...
I think shoud use like this 
```
(function () {
	var _jSmart;

	...

	if ( typeof module === "object" && module && typeof module.exports === "object" ) {
		module.exports = _jSmart;
	} else {
		global.jSmart = _jSmart;

		if ( typeof define === "function" && define.amd ) {
			define( "jSmart", [], function () { return _jSmart; } );
		}
	}

})();
```

**Comment by umakantp** [comment]
Okay, I get you. I'll get this plugged in the next release. Thanks

**Comment by jrszapata** [comment]
Excellent.

**Comment by umakantp** [comment]
Done in https://github.com/umakantp/jsmart/commit/a42cec7b92c2a3d49fd1a4835e4a24ef9f0359c0
