### ISSUE TITLE
strip_tags

### ISSUE THREAD

**Issue by gob33** [umakantp/jsmart#15]
in the strip_tags modifier, i dont understand your code:

``` javascript
return (new String(s)).replace(/<[^>]*?>/g, addSpace ? ' ' : '');
```

Would not it be:

``` javascript
return (new String(s)).replace(/<[^>]*>/g, addSpace ? ' ' : '');
```

without the '?'.

**Comment by gob33** [comment]
Reply to myself.
```javascript
/<[^>]*?>/g
```
is good (lazy quantifier "shortest match").

**Comment by umakantp** [comment]
This is not a feature of Smarty. The link you gave is of the user custom made plugin, which you can also build in jSmart.  Although I have added in jSmart, you can use the latest version which has this feature.
