### ISSUE TITLE
smarty comments don't work with some custom delimiters like {{ }}

### ISSUE THREAD

**Issue by rabuzarus** [umakantp/jsmart#17]
have a look  at http://www.smarty.net/docs/en/language.basic.syntax.tpl

`{* this is a comment for smarty *}`

At the present I use the original php templates for jsmart, so I don't have every of the many files twice. But I can't use them because they are full of comments which result in presenting empty delimiters (`{}`) in the output

edit:
OK I have to correct some things:

The Comments are working with the original delimiters. In our project we use `{{` and `}}` With this delimiters the comments don't work (the delimiters appear in the output). Look the post above

I will change the subject of this issue

**Comment by umakantp** [comment]
This has fixed in the latest version 3.0.0
