### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by mofux** [umakantp/jsmart#21]
When using this module through node.js, some of the checks for window do fail. The reason is that checking the existence of a global window object cannot be done via `if (window)`, because if window does not exist, it will throw an error. Instead, you should check for window existence via `if (typeof window === 'object')`, which will not throw.

I'm happy to create a PR if you like.

**Comment by mofux** [comment]
To be a bit more precise, this only happens when using modifiers in the template, because then the the failing code is executed.

**Comment by mofux** [comment]
Created PR #22 that should solve the problems.

**Comment by umakantp** [comment]
Thanks for filling the issue @mofux and creating the PR. I will review and take a merge and release the new minor version.
