### ISSUE TITLE
jSmart conditional & loop statement are not working with React-JS.

### ISSUE THREAD

**Issue by madoffcharles** [umakantp/jsmart#23]
In my React-JS Project, I am trying to use the smarty template. It is working for variables but it is not working at all for the loop and conditional statement. 
**I have following code written in my template :**
Following Data From Template 
&lt;div&gt;
Simple Data Passing &lt;br/&gt;
&lt;h1&gt;{$data}&lt;/h1&gt;
&lt;hr/&gt;
for loop code : &lt;br/&gt;
{$ar = ['a','b','c','d']}
{for $i=0 to $ar|count-1 max=3}
    {$ar[$i]}
{/for} 
&lt;hr /&gt;
if statement : &lt;br/&gt;
{assign var='xyz' value="1"}
{if '1' eq $xyz }
  if condition working 
{else}
  if condition is not working 
{/if}
&lt;/div&gt;

**Which is giving following output :**  
&lt;div&gt;Simple Data Passing &lt;br&gt;
&lt;h1&gt;Hello World&lt;/h1&gt;
&lt;hr&gt;
for loop code : &lt;br&gt;
 
&lt;hr&gt;
if statement : &lt;br&gt;
{if '1' eq $xyz }
  if condition working 
{else}
  if condition is not working 
{/if}
&lt;/div&gt;

Here I am passing the $data as "Hello World" it is working properly, but the below of for each is not working.
So could you please help me with this?

**Comment by umakantp** [comment]
You have to register count modifier yourself in the new jSmart version. It has been removed in new version like Smarty did. Here is smarty link documentation which shows no mention of |count modifier.


Below is an example of the count modifier:-

jsmart.prototype.registerPlugin(
    'modifier',
    'count',
    function (a) {
      return a.length;
    }
  );

**Comment by umakantp** [comment]
Hi @madoffcharles

I investigated and found that even though the count modifier documentation doesn't exist it still works in case of PHP Smarty.

In that case, I'm adding the count modifier again.

**Comment by umakantp** [comment]
Your if comes as it is because there is space at the end of curly brace in if statement
{if '1' eq **$xyz }**

It should be

{if '1' eq **$xyz}**

Read more about it on https://github.com/umakantp/jsmart/wiki/auto_literal

**Comment by umakantp** [comment]
Now that I have pushed changes and new version will be released with the fix i.e. having count method, I'closing the bug.
