### ISSUE TITLE
Unexpected [object Object] output when variable does not exist 

### ISSUE THREAD

**Issue by jwellner** [umakantp/jsmart#24]
I would expect it not to print [object Object] when the variable does not exist. Is this expected behavior or a bug? 

Code 
```
var jSmart = require('jsmart');

var compiledTemplate = new jSmart("Variable does not exist: {$variable}");
console.log(compiledTemplate.fetch({}));
```

Output:
```
Variable does not exist: [object Object]
```

**Comment by umakantp** [comment]
Hi 

@jwellner this is a bug and thanks for reporting. Ideally, it should print the blank string or 'undefined' string given that the variable is unassigned.

I will take a look at how Smarty PHP behaves.

Thanks

**Comment by umakantp** [comment]
Fixed the bug. Currently, if the variable is undefined, then it will return blank value just like how null does currently. New version will be released as soon as other bugs are fixed. Closing the ticket.

If you any questions, please feel to re-open the ticket. Thanks for reporting the bug.
