### ISSUE TITLE
 Assignment in a comparison is not functioning

### ISSUE THREAD

**Issue by ghost** [umakantp/jsmart#37]
**Template example**: "{if $info = "test"}{$info}{/if}"
**Expected result**: "test"
**Actual result**: empty string, no execution of code inside the "if" block.

This construction is functioning in PHP version of Smarty.

Code to reproduce:
<script>
    var templateText = '{if $info = "test"}{$info}{/if}';
    window.onload = function() {
        var template = new jSmart(templateText);
        document.getElementById('test').innerHTML = template.fetch();
    };
</script>

**Comment by umakantp** [comment]
Bug has been fixed in master, should be live in few days in npm
