### ISSUE TITLE
Built-in functions not running?

### ISSUE THREAD

**Issue by michaeljon** [umakantp/jsmart#39]
I'm assuming that I'm doing something completely wrong here. I'm trying to move some simple templates over to node. But, this one isn't firing and it's not clear from the docs or the source why this isn't working. I'm using 3.1.0

`const jsmart = require('jsmart');
const template = '<td><strong>Date Collected: </strong>{strtotime($collection_date)|date_format:"m/d/Y"}</td>';
const compiled = new jsmart(template);
console.log(compiled.fetch({ collection_date: '2020-01-01' }));`

 `<td><strong>Date Collected: </strong>m/d/Y</td>`

**Comment by umakantp** [comment]
strtotime is not defined in the JS/Node so it would not work. You will have to define the function yourself like

function strtotime() {
// write up here
}

You could refer the function here: https://locutus.io/php/datetime/strtotime/
