### ISSUE TITLE
{include file="./templates/header.html"} not working

### ISSUE THREAD

**Issue by edrobinson** [umakantp/jsmart#45]
JS Code:
var fs = require('fs'),
    path = require('path'),
    jSmart = require('jSmart');
    

var tpl = fs.readFileSync(path.join(process.cwd(),'/templates/Expenses.html'), {encoding: 'utf-8'});
console.log(tpl)
var compiledTemplate = new jSmart(tpl);
console.log(compiledTemplate.fetch({Title: "Expenses - jSmart"}));

The Expenses.html loads OK but the include above throws:

Error: No template for ./templates/header.html

Have tried all combinations of file names in the template file

**Comment by edrobinson** [comment]
Looked at the code:

    getTemplate: function (name) {
      throw new Error('No template for ' + name)
    },

There's a whole series of these not done functions. What gives?

**Comment by umakantp** [comment]
@edrobinson It is expected that you define that function. getTemplate has to be overridden and define as per environment like browser or node js.

‘’’
jSmart.prototype.getTemplate = (template) => {
  return loadedTpls[template]
}
’’’

loadedTpls could be populated using Ajax/fetch in browser while could be done be reading file in node js.

Here is another example in the docs: https://github.com/umakantp/jsmart/wiki/Include-Templates

**Comment by edrobinson** [comment]
Thank you for the fast reply. I can do this and get on with it.

**Comment by edrobinson** [comment]
Still no good life...
Node :
    fs = require('fs')
    jSmart = require('jsmart')
    //var js = new jSmart()
    jSmart.prototype.getTemplate = function(file){
        return fs.readFileSync('./templates/'+file, {encoding: 'utf-8'})
    }
        
    tpl = fs.readFileSync('./templates/Expenses.html', {encoding: 'utf-8'})
    compiledTemplate = new jSmart(tpl)
    output = compiledTemplate.fetch({title: 'Expenses - Smarty'})

    console.log("Compiled Template = " + output)

Node Output in Powershell:

C:\Users\Ed\nodestuff\node_modules\jsmart\dist\jsmart.js:1864
          var params = this.getActualParamValues(node.params, data)
                            ^

RangeError: Maximum call stack size exceeded
    at Object.process (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1864:29)
    at Object.process (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1553:58)
    at Object.getActualParamValues (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1658:20)
    at Object.process (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1864:29)
    at Object.process (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1553:58)
    at Object.getActualParamValues (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1658:20)
    at Object.process (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1864:29)
    at Object.process (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1553:58)
    at Object.getActualParamValues (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1658:20)
    at Object.process (C:\Users\Ed\nodestuff\node_modules\←[4mjsmart←[24m\dist\jsmart.js:1864:29)

Main HTML Template:
 {include header.html} 
  <body>
    {include nav.html}
    <div class="container">
        <form id="form1" name="form1" class="form_main" method="POST" action="/opts" style="padding-top: 15%">
            {include buttons.html}    
            <div class="form-group row">
                <label for="id" class="col-sm-4 col-form-label">Primary Key</label>
                <div class="col-sm-5">
                    <input type="number" class="form-control" id="id" name="id"/>
                </div>
                <input class="radio lb" type="radio" id="rpk" name="luby" value="id">
            </div>
            
            <div class="form-group row">
                <label for="exdate" class="col-sm-4 col-form-label">Date</label>
                <div class="col-sm-5">
                    <input type="date" class="form-control" id="exdate" name="exdate"/>
                </div>
                <input class="radio lb" type="radio" id="rdt" name="luby" value="exdate">  
            </div>
            
           <div class="form-group row">
                <label for="examt" class="col-sm-4 col-form-label">Amount</label>
                <div class="col-sm-5">
                    <input type="number" class="form-control" id="examt" name="examt"/>
                </div>
            <input class="radio lb" type="radio" id="ramt" name="luby" value="examt">
            </div>
            
            <div class="form-group row">
                <label for="exdescription" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="exdescription" name="exdescription"/>
                </div>
            <input class="radio lb" type="radio" id="rdesc" name="luby" value="exdescription">
            </div>
            
            <div class="form-group row">
                <label  class="col-sm-4 col-form-label">Catagory</label>
                <div class="col-sm-5">
                <select class="form-control"  name="excatagory" id="excatagory">
                <option ></option>
                {include CatagoryOptions.html}
                </select>
                </div>
                <input class="radio" type="radio" id="racid" name="luby" value="excatagory">
                <a class="btn btn-primary" href="/catagoriesindex" role="button">+</a>
            </div>
            
        </form>
  
    <div id="lookuplist" class="lookuplist">
        <select class="form-select" name="slookup" id="slookup" onchange="lookupProc(this)"></select>
    </div>
 
    </div> 
    
        {include myalert.html}


    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    
    <script src="/static/js/myalert.js"></script>
    <script src="/static/js/expenses.js"></script>
    <script src="/static/js/common.js"></script>
    
	{include footer.html}
 
  First include file - header.html:
<!DOCTYPE html>
<html lang="en" style="font-size: 14px;">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title}</title>
   
    
    
    
    
    
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/redmond/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/modal.css">   
    <link rel="stylesheet" href="/static/css/default.css">
   
    
    
  </head>

**Comment by edrobinson** [comment]
Found a malformed comment tag in the last include:

{{/* Content for the modal alert overlay */}}

Fixed it and life is good again.

Sorry to have been a pest...
