### ISSUE TITLE
Syntax error in readme.md

### ISSUE THREAD

**Issue by johannesgunnar** [umakantp/jsmart#9]
in the "How to use jSmart in Node.js" chapter in number 3 (and 4). Nothing major but was rather confusing to a JS/Node beginner like me. Took me a while to figure out what was wrong.

```
var fs = require(fs);
```

should be

```
var fs = require('fs');
```

**Comment by umakantp** [comment]
Thanks Jóhannes. I'll get it fixed.

**Comment by umakantp** [comment]
Done in https://github.com/umakantp/jsmart/commit/a1260b5de6e3b1990d1bf49c27045b24e8488846
